-- ============================================================================
-- EduMind Database Schema (PostgreSQL) - Module-Based LMS Architecture (CORE)
-- ============================================================================
-- Use this in Neon/Supabase/any Postgres server (3-tier demo).
--
-- Notes:
-- - Uses SERIAL-like identity columns.
-- - Uses BOOLEAN and TIMESTAMPTZ.
-- - Drops tables in dependency order.
-- ============================================================================

BEGIN;

DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS study_plan_items CASCADE;
DROP TABLE IF EXISTS study_plans CASCADE;
DROP TABLE IF EXISTS risk_scores CASCADE;
DROP TABLE IF EXISTS cv_reviews CASCADE;
DROP TABLE IF EXISTS quiz_results CASCADE;
DROP TABLE IF EXISTS quiz_questions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS assignment_attachments CASCADE;
DROP TABLE IF EXISTS assignment_submissions CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS course_materials CASCADE;
DROP TABLE IF EXISTS attendances CASCADE;
DROP TABLE IF EXISTS marks CASCADE;
DROP TABLE IF EXISTS student_module_progress CASCADE;
DROP TABLE IF EXISTS lecturer_modules CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS otps CASCADE;
DROP TABLE IF EXISTS intervention_messages CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS staff_profiles CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS lecturers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- USERS
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin','lecturer','student','career_advisor')),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_notification_read TIMESTAMPTZ,
  email_verified BOOLEAN DEFAULT FALSE,
  email_verification_token VARCHAR(100),
  email_verification_expires_at TIMESTAMPTZ,
  reset_token VARCHAR(100),
  reset_token_expires_at TIMESTAMPTZ
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

-- OTPS (email-based; no FK)
CREATE TABLE otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(120) NOT NULL,
  otp_code VARCHAR(6) NOT NULL,
  purpose VARCHAR(20) NOT NULL CHECK (purpose IN ('registration','password_reset')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  is_used BOOLEAN DEFAULT FALSE
);
CREATE INDEX idx_otps_email ON otps(email);
CREATE INDEX idx_otps_purpose ON otps(purpose);
CREATE INDEX idx_otps_expires_at ON otps(expires_at);

-- LECTURERS
CREATE TABLE lecturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  employee_id VARCHAR(20) NOT NULL UNIQUE,
  department VARCHAR(100),
  title VARCHAR(50),
  phone VARCHAR(20),
  office VARCHAR(50),
  hire_date DATE DEFAULT CURRENT_DATE,
  specialization VARCHAR(200)
);
CREATE INDEX idx_lecturers_user_id ON lecturers(user_id);
CREATE INDEX idx_lecturers_employee_id ON lecturers(employee_id);

-- STUDENTS
CREATE TABLE students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  student_id VARCHAR(20) NOT NULL UNIQUE,
  date_of_birth DATE,
  phone VARCHAR(20),
  address TEXT,
  program VARCHAR(100),
  year_of_study INTEGER,
  enrollment_date DATE DEFAULT CURRENT_DATE,
  profile_image VARCHAR(512)
);
CREATE INDEX idx_students_user_id ON students(user_id);
CREATE INDEX idx_students_student_id ON students(student_id);

-- STAFF PROFILES (for non-lecturer staff institutional login)
CREATE TABLE staff_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  staff_number VARCHAR(20) NOT NULL UNIQUE
);
CREATE INDEX idx_staff_profiles_user_id ON staff_profiles(user_id);
CREATE INDEX idx_staff_profiles_staff_number ON staff_profiles(staff_number);

-- COURSES / MODULES
CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  -- Credits may represent total programme credits (e.g. 120) in seed data
  credits INTEGER DEFAULT 3 CHECK (credits >= 0 AND credits <= 300),
  semester VARCHAR(20),
  year INTEGER DEFAULT EXTRACT(YEAR FROM NOW()),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_courses_code ON courses(code);
CREATE INDEX idx_courses_semester ON courses(semester);

CREATE TABLE modules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  module_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_modules_course_id ON modules(course_id);
CREATE INDEX idx_modules_order ON modules(module_order);

CREATE TABLE lecturer_modules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecturer_id BIGINT NOT NULL REFERENCES lecturers(id) ON DELETE CASCADE,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  is_primary BOOLEAN DEFAULT FALSE,
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (lecturer_id, module_id)
);
CREATE INDEX idx_lecturer_modules_lecturer_id ON lecturer_modules(lecturer_id);
CREATE INDEX idx_lecturer_modules_module_id ON lecturer_modules(module_id);

-- ENROLLMENTS
CREATE TABLE enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','completed','dropped')),
  enrolled_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  UNIQUE (student_id, course_id)
);
CREATE INDEX idx_enrollments_student_id ON enrollments(student_id);
CREATE INDEX idx_enrollments_course_id ON enrollments(course_id);
CREATE INDEX idx_enrollments_status ON enrollments(status);

-- MATERIALS
CREATE TABLE course_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  file_path VARCHAR(500),
  file_name VARCHAR(255),
  file_type VARCHAR(50),
  file_size BIGINT,
  category VARCHAR(50) CHECK (category IN ('lecture','assignment','reading','notes','other')),
  uploaded_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_materials_module_id ON course_materials(module_id);
CREATE INDEX idx_materials_category ON course_materials(category);

-- QUIZZES
CREATE TABLE quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  time_limit INTEGER,
  time_limit_seconds INTEGER,
  passing_score INTEGER DEFAULT 50 CHECK (passing_score BETWEEN 0 AND 100),
  is_published BOOLEAN DEFAULT FALSE,
  is_ai_generated BOOLEAN DEFAULT FALSE,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_quizzes_module_id ON quizzes(module_id);
CREATE INDEX idx_quizzes_published ON quizzes(is_published);

CREATE TABLE quiz_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  question_type VARCHAR(20) CHECK (question_type IN ('multiple_choice','true_false','short_answer')),
  points INTEGER DEFAULT 1,
  question_order INTEGER DEFAULT 0,
  options TEXT,
  correct_answer TEXT,
  acceptable_answers TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_questions_quiz_id ON quiz_questions(quiz_id);

CREATE TABLE quiz_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  score NUMERIC(10,2),
  total_points NUMERIC(10,2),
  percentage NUMERIC(5,2),
  passed BOOLEAN DEFAULT FALSE,
  time_taken INTEGER,
  answers TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);
CREATE INDEX idx_results_quiz_id ON quiz_results(quiz_id);
CREATE INDEX idx_results_student_id ON quiz_results(student_id);

-- ASSIGNMENTS
CREATE TABLE assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  due_date TIMESTAMPTZ,
  total_marks NUMERIC(10,2) DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_assignments_module_id ON assignments(module_id);
CREATE INDEX idx_assignments_due_date ON assignments(due_date);

CREATE TABLE assignment_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  file_path VARCHAR(500),
  file_name VARCHAR(255),
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  status VARCHAR(50) DEFAULT 'submitted',
  feedback TEXT,
  mark NUMERIC(10,2),
  grade VARCHAR(10),
  graded_at TIMESTAMPTZ,
  graded_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_submissions_assignment_id ON assignment_submissions(assignment_id);
CREATE INDEX idx_submissions_student_id ON assignment_submissions(student_id);

CREATE TABLE assignment_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  file_path VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_assignment_attachments_assignment_id ON assignment_attachments(assignment_id);

-- ATTENDANCE / MARKS
CREATE TABLE attendances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status VARCHAR(20) CHECK (status IN ('present','absent','late','excused')),
  recorded_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (student_id, module_id, date)
);
CREATE INDEX idx_attendances_module_id ON attendances(module_id);
CREATE INDEX idx_attendances_student_id ON attendances(student_id);
CREATE INDEX idx_attendances_date ON attendances(date);

CREATE TABLE marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  assessment_type VARCHAR(50) CHECK (assessment_type IN ('assignment','quiz','participation','project','midterm','final','other')),
  assessment_name VARCHAR(200),
  mark NUMERIC(10,2),
  total_marks NUMERIC(10,2),
  percentage NUMERIC(5,2),
  grade VARCHAR(5),
  recorded_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  feedback TEXT,
  marked_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_marks_module_id ON marks(module_id);
CREATE INDEX idx_marks_student_id ON marks(student_id);
CREATE INDEX idx_marks_assessment_type ON marks(assessment_type);

-- NOTIFICATIONS (model-aligned)
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(128) NOT NULL,
  message TEXT NOT NULL,
  priority VARCHAR(20) DEFAULT 'normal',
  action_url VARCHAR(255),
  action_text VARCHAR(64),
  entity_type VARCHAR(50),
  entity_id BIGINT,
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  metadata_json TEXT
);
CREATE INDEX idx_notifications_recipient_id ON notifications(recipient_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);

-- INTERVENTIONS (model-aligned)
CREATE TABLE intervention_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecturer_id BIGINT NOT NULL REFERENCES lecturers(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL,
  subject VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  template_used VARCHAR(50),
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  opened_at TIMESTAMPTZ,
  student_replied BOOLEAN DEFAULT FALSE,
  risk_level_at_send VARCHAR(20),
  recommended_actions TEXT
);
CREATE INDEX idx_interventions_student_id ON intervention_messages(student_id);
CREATE INDEX idx_interventions_lecturer_id ON intervention_messages(lecturer_id);
CREATE INDEX idx_interventions_sent_at ON intervention_messages(sent_at);

COMMIT;

